/**
 * Esta clase la hemos definido para que herede el docigo de la clase
 * jframe de java, la cual ya viene programada para que se comporte como una 
 * Ventana normal del sistema Operativo. Es decir, una ventana  que tiene:
 * Barra de titulo
 * Border
 * Botones para Minimizar , Maximizar, Restaurar y Cerrar
 * Incono en la esquina parte seperior
 * un papel de fondo en el que podemos colocar otros componentes
* Una barra de menu para agregarle menus, y a estos poder agregarles opciones
* al ser una ventana normal del S.O, esta tambien podemos:
* Abrirla, Ocultarla de una lado a otrp, estiarla, Maximizarla, Moverla y Arrastrarla de un lado a otro, estiarla, escojerla,
* Cambiarle el color e imagen de fondo, colocarle un icono identificativo, etc
 * 
 */
package millervargas.ejemplodb.v1.ventanas;

/**
 *
 * @author gasler
 */
public class VentanaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
